<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <Version>1.0.57</Version>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>NeoAdmin.Blazor</AssemblyName>
    <RootNamespace>NeoAdmin.Blazor</RootNamespace>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Description>NeoAdmin.Blazor 的基础框架骨架。</Description>
    <Title>NeoAdmin.Blazor</Title>
    <Product>NeoAdmin.Blazor</Product>
    <PackageId>NeoAdmin.Blazor</PackageId>
    <Authors>NeoAdmin</Authors>
    <PackageTags>blazor;blazor-server;admin;freesql;neoui;neoadmin</PackageTags>
    <RepositoryUrl>https://github.com/3bDjrvHs50kiZIJb5/NeoAdminProject</RepositoryUrl>
    <PackageProjectUrl>https://github.com/3bDjrvHs50kiZIJb5/NeoAdminProject</PackageProjectUrl>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="logo.png" Pack="true" PackagePath="\" Visible="false" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Aliyun.OSS.SDK.NetCore" Version="2.14.1" />
    <PackageReference Include="DiceBear.Core" Version="10.7.0" />
    <PackageReference Include="DiceBear.Styles" Version="10.6.0" />
    <PackageReference Include="FreeSql" Version="3.5.304" />
    <PackageReference Include="FreeSql.Provider.SqliteCore" Version="3.5.304" />
    <PackageReference Include="FreeScheduler" Version="2.1.4" />
    <PackageReference Include="NCrontab" Version="3.4.0" />
    <PackageReference Include="NeoUI.Blazor" Version="4.1.7" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Rougamo.Fody" Version="5.0.2" />
    <PackageReference Include="Yitter.IdGenerator" Version="1.0.14" />
  </ItemGroup>
</Project>
